/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hunter;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

/**
 *
 * @author jingweizhang
 */
public class TeamExisited extends javax.swing.JPanel {

    /**
     * Creates new form TeamExisited
     */
    public TeamExisited() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Bob Fcku
    private void initComponents() {
        teamNameLabel = new JLabel();
        teamName = new JLabel();
        teamMemberList = new JScrollPane();
        jList1 = new JList<>();
        levelLabel = new JLabel();
        rankLabel = new JLabel();
        teamLevel = new JLabel();
        teamRank = new JLabel();
        teamMemberLabel = new JLabel();
        currentMissionList = new JScrollPane();
        jList2 = new JList<>();
        currentMissionLabel = new JLabel();
        memberNameLabel = new JLabel();
        memberName = new JLabel();
        memberLevelLabel = new JLabel();
        memberLevel = new JLabel();
        memberRankLabel = new JLabel();
        memberRank = new JLabel();
        experienceLabel = new JLabel();
        memberExp = new JLabel();

        //======== this ========

        // JFormDesigner evaluation mark
        setBorder(new javax.swing.border.CompoundBorder(
            new javax.swing.border.TitledBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0),
                "JFormDesigner Evaluation", javax.swing.border.TitledBorder.CENTER,
                javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                java.awt.Color.red), getBorder())); addPropertyChangeListener(new java.beans.PropertyChangeListener(){public void propertyChange(java.beans.PropertyChangeEvent e){if("border".equals(e.getPropertyName()))throw new RuntimeException();}});


        //---- teamNameLabel ----
        teamNameLabel.setText("TeamName:");

        //---- teamName ----
        teamName.setText("Gecko Express ");

        //======== teamMemberList ========
        {

            //---- jList1 ----
            jList1.setModel(new AbstractListModel<String>() {
                String[] values = {
                    "Item 1",
                    "Item 2",
                    "Item 3",
                    "Item 4",
                    "Item 5"
                };
                @Override
                public int getSize() { return values.length; }
                @Override
                public String getElementAt(int i) { return values[i]; }
            });
            teamMemberList.setViewportView(jList1);
        }

        //---- levelLabel ----
        levelLabel.setText("TeamLevel: ");

        //---- rankLabel ----
        rankLabel.setText("TeamRank: ");

        //---- teamLevel ----
        teamLevel.setText("XXX");

        //---- teamRank ----
        teamRank.setText("XX");

        //---- teamMemberLabel ----
        teamMemberLabel.setText("Team Members:");

        //======== currentMissionList ========
        {

            //---- jList2 ----
            jList2.setModel(new AbstractListModel<String>() {
                String[] values = {
                    "Item 1",
                    "Item 2",
                    "Item 3",
                    "Item 4",
                    "Item 5"
                };
                @Override
                public int getSize() { return values.length; }
                @Override
                public String getElementAt(int i) { return values[i]; }
            });
            currentMissionList.setViewportView(jList2);
        }

        //---- currentMissionLabel ----
        currentMissionLabel.setText("CURRENT MISSIONS:");

        //---- memberNameLabel ----
        memberNameLabel.setText("Name:");

        //---- memberName ----
        memberName.setText("Jingwei Zhang");

        //---- memberLevelLabel ----
        memberLevelLabel.setText("Level:");

        //---- memberLevel ----
        memberLevel.setText("XXX");

        //---- memberRankLabel ----
        memberRankLabel.setText("Rank:");

        //---- memberRank ----
        memberRank.setText("XXX");

        //---- experienceLabel ----
        experienceLabel.setText("Experience:");

        //---- memberExp ----
        memberExp.setFont(new Font("Lucida Grande", Font.PLAIN, 8));
        memberExp.setText("2333/45000");

        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup()
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup()
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(teamNameLabel)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(teamName))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(levelLabel)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(teamLevel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rankLabel)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(teamRank))
                                .addComponent(teamMemberLabel))
                            .addGap(18, 18, 18))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(teamMemberList, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup()
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup()
                                        .addComponent(memberNameLabel)
                                        .addComponent(memberLevelLabel))
                                    .addGroup(layout.createParallelGroup()
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(memberName))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(memberLevel))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup()
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(memberRankLabel)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(memberRank))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(experienceLabel)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(memberExp)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createParallelGroup()
                        .addComponent(currentMissionList)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(currentMissionLabel)
                            .addGap(0, 8, Short.MAX_VALUE)))
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup()
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(teamNameLabel)
                        .addComponent(teamName)
                        .addComponent(currentMissionLabel))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup()
                        .addComponent(currentMissionList, GroupLayout.PREFERRED_SIZE, 293, GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(levelLabel)
                                .addComponent(teamLevel))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(rankLabel)
                                .addComponent(teamRank))
                            .addGap(97, 97, 97)
                            .addComponent(teamMemberLabel)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup()
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(memberNameLabel)
                                        .addComponent(memberName))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(memberLevelLabel)
                                        .addComponent(memberLevel))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(memberRankLabel)
                                        .addComponent(memberRank))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(experienceLabel)
                                        .addComponent(memberExp, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(teamMemberList, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))))
                    .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Bob Fcku
    private JLabel teamNameLabel;
    private JLabel teamName;
    private JScrollPane teamMemberList;
    private JList<String> jList1;
    private JLabel levelLabel;
    private JLabel rankLabel;
    private JLabel teamLevel;
    private JLabel teamRank;
    private JLabel teamMemberLabel;
    private JScrollPane currentMissionList;
    private JList<String> jList2;
    private JLabel currentMissionLabel;
    private JLabel memberNameLabel;
    private JLabel memberName;
    private JLabel memberLevelLabel;
    private JLabel memberLevel;
    private JLabel memberRankLabel;
    private JLabel memberRank;
    private JLabel experienceLabel;
    private JLabel memberExp;
    // End of variables declaration//GEN-END:variables
}
