/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MissionHolder;

import Main.Connector;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MalcolmChen
 */
public class MissionStats extends javax.swing.JFrame {
    private static int itemMission=1000;
   
    private Connection con;
    private Statement stmt;
    private ResultSet rs;
    private ResultSet rs2;
    private int id;
    private PreparedStatement pst;
    /**
     * Creates new form MissionStats
     */
    public MissionStats(int id) {
        initComponents();
        this.id=id;
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        con=Connector.getConnection();
        setcurrentMissionTable();
    }
    
    public void setcurrentMissionTable(){
        DefaultTableModel item1=(DefaultTableModel)ItemTable1.getModel();
        DefaultTableModel hunter1=(DefaultTableModel) huntingtable1.getModel();
        Object item1data[]=new Object[6];
        try{
            stmt= con.createStatement();
            String imissionQuery="select * from Item_Foraging_Mission where  missionHolderID="+id;
            rs=stmt.executeQuery(imissionQuery);
            while(rs.next()){
                item1data[0]=rs.getInt(1);
                item1data[1]=rs.getInt(2);
                item1data[2]=rs.getString("startTime");
                item1data[3]=rs.getString("deadline");
                item1data[4]=rs.getString("acceptTime");
                int missionid=rs.getInt(1);
                String itemQuery="select ItemId from IMission_has_Item where itemMissionId="+missionid;
                rs2=stmt.executeQuery(itemQuery);
                rs2.next();
                int itemid=rs2.getInt("ItemId");
                String itemNameQuery="select itemName from item where itemID="+itemid;
                rs2=stmt.executeQuery(itemNameQuery);
                rs2.next();
                item1data[5]=rs2.getString(1);
                item1.addRow(item1data);
               
            }
             //for current HunterMission
            String hmissionQuery="select * from Hunting_missions where  missionHolderID="+id;
            ResultSet rs = stmt.executeQuery(hmissionQuery);
            
            while(rs.next()){
                item1data[0]=rs.getInt(1);
                Integer count = null;
                count=rs.getInt(2);
                item1data[1]=count;
                item1data[2]=rs.getString("startTime");
                item1data[3]=rs.getString("deadline");
                item1data[4]=rs.getString("acceptTime");
                int missionid=rs.getInt(1);
                String monsQuery="select monsterid from MMission_has_Monster where huntingMissionId="+missionid;
                rs2=stmt.executeQuery(monsQuery);
                rs2.next();
                int monsid=rs2.getInt("monsterid");
                String itemNameQuery="select name from Monster where monsterid="+monsid;
                rs2=stmt.executeQuery(itemNameQuery);
                rs2.next();
                item1data[5]=rs2.getString(1);
                hunter1.addRow(item1data);
               
            }    
                
           
            
            
        }catch(SQLException err){
            System.out.print(err);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        ItemTable1 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        huntingtable1 = new javax.swing.JTable();
        mMissionStatsBackButton = new javax.swing.JButton();
        mManageMissionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mission History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24), new java.awt.Color(0, 0, 153))); // NOI18N

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jTabbedPane2.addTab("tab1", jScrollPane5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jTabbedPane2.addTab("tab2", jScrollPane6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Current Mission", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ItemTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hunter ID", "Start Time", "Deadline", "Accept Time", "Item"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(ItemTable1);
        if (ItemTable1.getColumnModel().getColumnCount() > 0) {
            ItemTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jTabbedPane1.addTab("Item-Foraging Mission", jScrollPane4);

        huntingtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hunter ID", "Start Time", "Deadline", "Accept Time", "Monster"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(huntingtable1);
        if (huntingtable1.getColumnModel().getColumnCount() > 0) {
            huntingtable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jTabbedPane1.addTab("Hunting Mission", jScrollPane7);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 32, 835, 315));

        mMissionStatsBackButton.setText("Back");
        mMissionStatsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMissionStatsBackButtonActionPerformed(evt);
            }
        });

        mManageMissionButton.setText("Manage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(mMissionStatsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(mManageMissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMissionStatsBackButton)
                    .addComponent(mManageMissionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mMissionStatsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMissionStatsBackButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_mMissionStatsBackButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ItemTable1;
    private javax.swing.JTable huntingtable1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JButton mManageMissionButton;
    private javax.swing.JButton mMissionStatsBackButton;
    // End of variables declaration//GEN-END:variables
}
