/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MissionHolder;


import Leaderboard.LeaderBoardPanel;
import Main.Connector;
import static Main.Connector.closeConnection;
import static Main.Connector.getConnection;
import Main.signup;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author MalcolmChen
 */
public class MissionHolderHome extends javax.swing.JFrame {
    private int id;
    
    private Connection con;
    private Statement stmt;
    private ResultSet rs;
    
    /**
     * Creates new form MissionHolderHome
     */
    public MissionHolderHome(int id) {
        this.id=id;
        con = getConnection();
        
        initComponents();
        setById(id);        
    }
    
    public void setById(int id){
        IDtext.setText("id: "+id);
        
        con = getConnection();
        
        try{
            stmt= con.createStatement();
            String nameQuery="select name from missionholder where  MISSIONHOLDERID="+id;
            rs=stmt.executeQuery(nameQuery);
            rs.next();
            
            NameText.setText(rs.getString(1));
            
            String ageQuery="select age from missionholder where  MISSIONHOLDERID="+id;
            rs=stmt.executeQuery(ageQuery);
            rs.next();
            agetext.setText("Age: "+rs.getInt(1));
            String balanceQuery="select GOLDBALANCE from missionholder where  MISSIONHOLDERID="+id;
            rs=stmt.executeQuery(balanceQuery);
            rs.next();
            int balance=rs.getInt(1);
            BalanceText.setText("Balance: "+balance);
            if(balance>10000000){
                rank.setText("S");
            }else if(balance>100000){
                rank.setText("A");
            }else if(balance>50000){
                rank.setText("B");
            }else if(balance>10000){
                rank.setText("C");
            }else if(balance>5000){
                rank.setText("D");
            }else{
                rank.setText("-");
            }
        }catch(SQLException err){
            System.out.print(err);
        }
        
        closeConnection();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rank = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mNewMissionButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        mMissionStatsButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mLeaderBoardButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        AddMoneyButton = new javax.swing.JButton();
        MoneyToAddText = new javax.swing.JTextField();
        BalanceText = new javax.swing.JLabel();
        agetext = new javax.swing.JLabel();
        IDtext = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        NameText = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(246, 245, 245));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("#WELCOME,");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MissionHolder/head.jpg"))); // NOI18N

        rank.setFont(new java.awt.Font("Luminari", 1, 70)); // NOI18N
        rank.setForeground(new java.awt.Color(204, 204, 0));
        rank.setText("S");

        jPanel1.setBackground(new java.awt.Color(246, 245, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)), "Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24), new java.awt.Color(0, 153, 153))); // NOI18N

        mNewMissionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MissionHolder/vision_mission.jpg"))); // NOI18N
        mNewMissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNewMissionButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("LeaderBoards");

        mMissionStatsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MissionHolder/stat.png"))); // NOI18N
        mMissionStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMissionStatsButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("New Mission");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Mission Stats");

        mLeaderBoardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MissionHolder/leaderboard-300x300.png"))); // NOI18N
        mLeaderBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLeaderBoardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(mNewMissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mMissionStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)))
                .addGap(137, 137, 137)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mLeaderBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mNewMissionButton)
                        .addComponent(mLeaderBoardButton))
                    .addComponent(mMissionStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(246, 245, 245));

        AddMoneyButton.setText("AddMoney");
        AddMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMoneyButtonActionPerformed(evt);
            }
        });

        MoneyToAddText.setForeground(new java.awt.Color(102, 102, 102));
        MoneyToAddText.setToolTipText("Enter Money");
        MoneyToAddText.setMinimumSize(new java.awt.Dimension(13, 26));
        MoneyToAddText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MoneyToAddTextFocusGained(evt);
            }
        });
        MoneyToAddText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyToAddTextActionPerformed(evt);
            }
        });

        BalanceText.setText("Balance: ");

        agetext.setText("Age: ");

        IDtext.setText("ID: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agetext)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BalanceText)
                        .addGap(63, 63, 63)
                        .addComponent(MoneyToAddText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(AddMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IDtext)
                .addGap(25, 25, 25)
                .addComponent(agetext)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(BalanceText))
                    .addComponent(MoneyToAddText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(AddMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MissionHolder/075fbc8094149.560b71bb6d238.png"))); // NOI18N
        refresh.setBorder(null);
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        NameText.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        NameText.setForeground(new java.awt.Color(153, 0, 51));
        NameText.setText("Ricardo·M·Lu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(rank)
                                .addGap(47, 47, 47)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rank))
                    .addComponent(refresh)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("About");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
              // TODO add your handling code here:
              setVisible(false);
              new signup().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mMissionStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMissionStatsButtonActionPerformed
        // TODO add your handling code here:
        MissionStats missionStatPanel =new MissionStats(id);
        missionStatPanel.setVisible(true);
    }//GEN-LAST:event_mMissionStatsButtonActionPerformed

    private void mLeaderBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLeaderBoardButtonActionPerformed
        JFrame frame = new JFrame();
        LeaderBoardPanel lb = new LeaderBoardPanel();
        frame.add(lb);
        frame.setSize(1200,600);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_mLeaderBoardButtonActionPerformed

    private void mNewMissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNewMissionButtonActionPerformed
        TypeChosing createMissionPanel = new TypeChosing(id);
        createMissionPanel.setVisible(true);        
    }//GEN-LAST:event_mNewMissionButtonActionPerformed

    private void AddMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMoneyButtonActionPerformed
        // TODO add your handling code here:
        int addMoney = Integer.parseInt(MoneyToAddText.getText());
        
        con = getConnection();
        
        try {
            stmt= con.createStatement();
            String balanceQuery = "select GOLDBALANCE from missionholder where  MISSIONHOLDERID=" + id;
            rs = stmt.executeQuery(balanceQuery);
            rs.next();
            int currentBalance =rs.getInt(1);
            int newBalance=currentBalance+addMoney;
            String updateBalance="UPDATE missionholder SET GOLDBALANCE="+newBalance+" WHERE MISSIONHOLDERID=" + id;
            stmt.executeUpdate(updateBalance);
            rs=stmt.executeQuery(balanceQuery);
            rs.next();
            BalanceText.setText("Balance: "+rs.getInt(1));
        } catch (SQLException err) {
            System.out.print(err);
        }
        closeConnection();
    }//GEN-LAST:event_AddMoneyButtonActionPerformed

    private void MoneyToAddTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyToAddTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyToAddTextActionPerformed

    private void MoneyToAddTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MoneyToAddTextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyToAddTextFocusGained

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        setById(id);
    }//GEN-LAST:event_refreshActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMoneyButton;
    private javax.swing.JLabel BalanceText;
    private javax.swing.JLabel IDtext;
    private javax.swing.JTextField MoneyToAddText;
    private javax.swing.JLabel NameText;
    private javax.swing.JLabel agetext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton mLeaderBoardButton;
    private javax.swing.JButton mMissionStatsButton;
    private javax.swing.JButton mNewMissionButton;
    private javax.swing.JLabel rank;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
