/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MissionHolder;

import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author MalcolmChen
 */
public class TypeChosing extends javax.swing.JFrame {
    private int id;
    /**
     * Creates new form NewMission
     */
    public TypeChosing(int id) {
        this.id=id;
        initComponents();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mConfirmCreateMissionButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        mHuntingMissionButton = new javax.swing.JRadioButton();
        mItemMissionButton = new javax.swing.JRadioButton();
        mTypeSelectBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mConfirmCreateMissionButton.setText("CREATE");
        mConfirmCreateMissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConfirmCreateMissionButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 2), "Select the Type Of Mission", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(153, 0, 153))); // NOI18N

        buttonGroup1.add(mHuntingMissionButton);
        mHuntingMissionButton.setText("Hunting Mission");
        mHuntingMissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHuntingMissionButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(mItemMissionButton);
        mItemMissionButton.setText("Item Mission");
        mItemMissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemMissionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mItemMissionButton)
                .addGap(33, 33, 33)
                .addComponent(mHuntingMissionButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mItemMissionButton)
                    .addComponent(mHuntingMissionButton))
                .addContainerGap())
        );

        mTypeSelectBackButton.setText("Back");
        mTypeSelectBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTypeSelectBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(mTypeSelectBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mConfirmCreateMissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mConfirmCreateMissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mTypeSelectBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mItemMissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemMissionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemMissionButtonActionPerformed

    private void mHuntingMissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHuntingMissionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mHuntingMissionButtonActionPerformed

    private void mConfirmCreateMissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConfirmCreateMissionButtonActionPerformed
        // TODO add your handling code here:
        if(mItemMissionButton.isSelected()){
            setVisible(false);
            ItemMission haha=new ItemMission(id);
            haha.setVisible(true);
        }else if(mHuntingMissionButton.isSelected()){
            setVisible(false);
            HuntingMission hehe=new HuntingMission(id);
            hehe.setVisible(true);
        }
    }//GEN-LAST:event_mConfirmCreateMissionButtonActionPerformed

    private void mTypeSelectBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTypeSelectBackButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_mTypeSelectBackButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mConfirmCreateMissionButton;
    private javax.swing.JRadioButton mHuntingMissionButton;
    private javax.swing.JRadioButton mItemMissionButton;
    private javax.swing.JButton mTypeSelectBackButton;
    // End of variables declaration//GEN-END:variables
}
